apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rs
spec:
  selector:
    matchLabels:
      env: production

  replicas: 1
  template:
    metadata:
      labels:
        env: production

    spec:
      containers:
      - name: httpd-container
        image: httpd

        ports:
        - containerPort: 80

        volumeMounts:
          - name: httpd-data-pvc
            mountPath: /usr/local/apache2/htdocs/

        volumeMounts:
          - name: httpd-logs-pvc
            mountPath: /var/log/httpd/

      volumes:
      - name: httpd-data-pvc
        persistentVolumeClaim:
          claimName: httpd-data-pvc1

      volumes:
      - name: httpd-logs-pvc
        persistentVolumeClaim:
          claimName: httpd-logs-pvc1
