---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: httpd-data-pvc1
  labels:
    env: production
spec:
  accessModes:
   - ReadWriteMany
  resources:  
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: httpd-log-pvc1
  labels:
    env: production
spec:
  accessModes:
   - ReadWriteMany
  resources:  
    requests:
      storage: 2Gi
---

    
