apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: NodePort
  selector:
    env: production
  ports:
  - port: 8085
    targetPort: 80
    nodePort: 31000
    protocol: TCP
    name: web-port


